version: '3'

services:
  mysql:
    image: docker.io/mysql:5.7
    restart: always
    env_file: .env
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - '127.0.0.1:33060:3306'
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile        
    volumes:
      - ./backend:/opt/app:delegated
    ports:
      - '127.0.0.1:8080:8080'
    networks:
      - app_network
    depends_on:
      - mysql
    env_file: .env
    # add an argument to the command below and it won't try to recreate the tables
    command: /bin/bash seedDatabase/seedDatabase.sh

volumes:
  mysql_volume:

networks:
  app_network:
    driver: bridge